spring:
  kafka:
    kafka-server: localhost:9092
resilience4j:
  circuitbreaker:
    instances:
      productService:
        # 40% 이상의 실패율이면 OPEN 상태로 변경
        failureRateThreshold: 40  
        # 40% 이상의 요청이 느리면 OPEN 상태로 변경
        slowCallRateThreshold: 40  
        # 2초 이상 걸리면 느린 호출로 간주
        slowCallDurationThreshold: 2s  
        # OPEN 상태에서 10초 동안 차단 후 HALF-OPEN 상태로 변경
        waitDurationInOpenState: 10s  
        # HALF-OPEN 상태에서 2개 요청이 모두 성공하면 → CLOSED 상태로 변경
        permittedNumberOfCallsInHalfOpenState: 2  
        # 최근 5개의 요청을 기준으로 실패율 계산
        slidingWindowSize: 5  
        # 요청 개수를 기준으로 실패율을 계산하도록 설정
        slidingWindowType: COUNT_BASED 
        # 최소 정상적인 요청을 4번 실행된 이후 Circuit Breaker 활성화
        minimumNumberOfCalls: 4  
        ignoreExceptions:
          - java.lang.IllegalArgumentException  